<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <IsTestProject>true</IsTestProject>
    <Nullable>disable</Nullable>
    <ShouldRemoveRhinoReferences>True</ShouldRemoveRhinoReferences>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Grasshopper" Version="8.21.25188.17001" Private="False" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="RhinoCommon" Version="8.21.25188.17001" Private="False" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="Rhino.Testing" Version="8.0.28-beta" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Rhino.Testing.Configs.xml" CopyToOutputDirectory="Always" />
  </ItemGroup>
</Project>
