"""Wire the generated 24x24 PNGs into this repository's Grasshopper projects, using each project's EXISTING icon mechanism.

Per project (project_dir from the manifest):
  * copies png/24/<icon_id>.png -> <project>/Resources/Icons/<Resource>.png (only the icons that project uses)
  * mechanism "resx" (SAM convention): ResXFileRef entries in Properties/Resources.resx + strongly-typed properties in
    Properties/Resources.Designer.cs, typed byte[] or Bitmap to match the resources the project's Icon getters use today
  * mechanism "holder" (e.g. SAMOCCTIcon): generated properties inside `// <sam-gh-icons>` markers of the holder class,
    loading manifest resources the same way the holder already does, plus one csproj EmbeddedResource line
  * replaces the icon token inside each component's `Icon` getter (Resources.OLD -> Resources.NEW); nothing else.
Idempotent: re-running replaces previously generated SAM_GH_* entries. Old resources are left untouched.
"""
import json
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DESIGN = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(DESIGN))
PNG = os.path.join(DESIGN, "png", "24")
PREFIX = "SAM_GH_"

TYPE_BITMAP = "System.Drawing.Bitmap, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
TYPE_BYTES = "System.Byte[], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"


def read(p):
    raw = open(p, "rb").read()
    bom = raw.startswith(b"\xef\xbb\xbf")
    text = raw.decode("utf-8-sig")
    nl = "\r\n" if "\r\n" in text else "\n"
    return text.replace("\r\n", "\n"), bom, nl


def write(p, text, bom, nl):
    data = text.replace("\n", nl).encode("utf-8")
    open(p, "wb").write((b"\xef\xbb\xbf" if bom else b"") + data)


# ------------------------------------------------------------------ resx mechanism (identical to SAM#166)
def update_resx(path, names, as_bytes):
    text, bom, nl = read(path)
    text = re.sub(r'  <data name="' + PREFIX + r'\w+" type="System\.Resources\.ResXFileRef, System\.Windows\.Forms">\n    <value>[^<]*</value>\n  </data>\n', "", text)
    t = TYPE_BYTES if as_bytes else TYPE_BITMAP
    entries = "".join(
        f'  <data name="{n}" type="System.Resources.ResXFileRef, System.Windows.Forms">\n'
        f'    <value>..\\Resources\\Icons\\{n}.png;{t}</value>\n  </data>\n' for n in sorted(names))
    text = text.replace("</root>", entries + "</root>")
    write(path, text, bom, nl)


def update_designer(path, names, as_bytes):
    text, bom, nl = read(path)
    text = re.sub(r"        \n        /// <summary>\n        ///   Looks up a localized resource of type [^\n]+\n        /// </summary>\n"
                  r"        (?:internal|public) static [^\n]+ " + PREFIX + r"\w+ \{\n(?:            [^\n]*\n)+        \}\n", "", text)
    typ = "byte[]" if as_bytes else "System.Drawing.Bitmap"
    # match the generator in use (ResXFileCodeGenerator = internal, PublicResXFileCodeGenerator = public)
    vis = "public" if re.search(r"\n        public static [\w.\[\]]+ \w+\s*\{\s*\n\s*get", text) else "internal"
    kind = "System.Byte[]" if as_bytes else "System.Drawing.Bitmap"
    props = "".join(
        f"        \n        /// <summary>\n        ///   Looks up a localized resource of type {kind}.\n        /// </summary>\n"
        f"        {vis} static {typ} {n} {{\n            get {{\n"
        f"                object obj = ResourceManager.GetObject(\"{n}\", resourceCulture);\n"
        f"                return (({typ})(obj));\n            }}\n        }}\n" for n in sorted(names))
    idx = text.rstrip().rfind("}")  # namespace close
    idx = text.rfind("    }", 0, idx)  # class close
    text = text[:idx].rstrip(" ") + props + text[idx:]
    write(path, text, bom, nl)


def resource_is_bytes(designer, name):
    """Type of an existing resource in Resources.Designer.cs (True = byte[], False = Bitmap)."""
    text = read(designer)[0]
    m = re.search(r"(?:internal|public) static ([\w.\[\]]+) " + re.escape(name) + r"\s*\{", text)
    assert m, (designer, name)
    return m.group(1) == "byte[]"


# ------------------------------------------------------------------ holder mechanism (manifest-resource icon class)
def update_holder(holder_path, names, csproj):
    text, bom, nl = read(holder_path)
    m = re.search(r'GetManifestResourceStream\("([\w.]+)\.Resources\.\w+\.png"\)', text)
    assert m, holder_path
    root = m.group(1)
    text = re.sub(r"\n[ \t]*// <sam-gh-icons>.*?// </sam-gh-icons>\n", "\n", text, flags=re.S)
    cls = re.search(r"\n([ \t]*)(?:internal|public) static class \w+\s*\n\1\{\n", text)
    ind = cls.group(1) + "    "
    body = [f"{ind}// <sam-gh-icons> generated by design/grasshopper-icons/tools/integrate.py (SAM GH icon redesign)",
            f"{ind}private static Bitmap LoadIcon(string name)", f"{ind}{{",
            f"{ind}    using (Stream stream = typeof({re.search(r'static class (\w+)', text).group(1)}).Assembly.GetManifestResourceStream(\"{root}.Resources.Icons.\" + name + \".png\"))",
            f"{ind}    {{", f"{ind}        if (stream == null)", f"{ind}        {{", f"{ind}            return null;", f"{ind}        }}", "",
            f"{ind}        using (Bitmap bitmap = new Bitmap(stream))", f"{ind}        {{", f"{ind}            return new Bitmap(bitmap);",
            f"{ind}        }}", f"{ind}    }}", f"{ind}}}", ""]
    body += [f"{ind}internal static Bitmap {n} => LoadIcon(\"{n}\");" for n in sorted(names)]
    body += [f"{ind}// </sam-gh-icons>"]
    close = text.rfind("\n" + cls.group(1) + "}")  # class close brace
    text = text[:close] + "\n\n" + "\n".join(body) + text[close:]
    write(holder_path, text, bom, nl)
    ctext, cbom, cnl = read(csproj)
    line = '<EmbeddedResource Include="Resources\\Icons\\SAM_GH_*.png" />'
    if line not in ctext:
        mm = re.search(r'\n([ \t]*)<EmbeddedResource Include="Resources\\[^"]+\.png" />', ctext)
        assert mm, csproj
        ctext = ctext[:mm.end()] + "\n" + mm.group(1) + line + ctext[mm.end():]
        write(csproj, ctext, cbom, cnl)


# ------------------------------------------------------------------ Icon getter
CLASS_DECL = r"^\s*(?:\[[^\]]*\]\s*)*(?:public|internal)[\w\s]*\bclass\s+{}\b"


def update_icon(src_path, cls, holder, resource, guid, bytes_expr=None):
    text, bom, nl = read(src_path)
    # locate the class by its (unique) ComponentGuid: a file may declare the same class name twice
    gpos = re.search(r'ComponentGuid[^\n]*"' + re.escape(guid) + '"', text, re.I)
    assert gpos, (src_path, cls, guid)
    m = None
    for mm in re.finditer(CLASS_DECL.format(cls), text[:gpos.start()], re.M):
        m = mm
    assert m, (src_path, cls)
    nxt = re.search(r"^\s*(?:public|internal)[\w\s]*\bclass\s+\w+", text[m.end():], re.M)
    end = m.end() + nxt.start() if nxt else len(text)
    body = text[m.end():end]
    ic = re.search(r"override\s+(?:System\.Drawing\.)?Bitmap\s+Icon\b", body)
    assert ic, (src_path, cls, "no Icon override")
    seg_start = ic.end()
    seg = body[seg_start: seg_start + 300]
    # first <holder>.X that is not inside a // comment
    hit = next((mm for mm in re.finditer(r"\b" + re.escape(holder) + r"\.\w+", seg)
                if "//" not in seg[seg.rfind("\n", 0, mm.start()) + 1: mm.start()]), None)
    assert hit, (src_path, cls)
    new_seg = seg[:hit.start()] + holder + "." + resource + seg[hit.end():]
    body = body[:seg_start] + new_seg + body[seg_start + 300:]
    text = text[:m.end()] + body + text[end:]
    write(src_path, text, bom, nl)


def verify(rows):
    """Re-parse the C# source: every object must now reference its manifest resource, and the PNG must exist."""
    raw_path = os.path.join(DESIGN, "manifest_raw.json")
    original = open(raw_path, "rb").read()  # keep the pre-redesign inventory (records the old icons)
    try:
        subprocess.run([sys.executable, os.path.join(HERE, "inventory.py")], check=True, stdout=subprocess.DEVNULL)
        now = {r["guid"] + "|" + r["source"]: r for r in json.load(open(raw_path, encoding="utf-8"))}
    finally:
        open(raw_path, "wb").write(original)
    bad = []
    for r in rows:
        cur = now[r["guid"] + "|" + r["source"]]["icon_expr"]
        png = os.path.join(REPO, r["project_dir"], "Resources", "Icons", r["resource"] + ".png")
        if cur != r["resource"] or not os.path.isfile(png):
            bad.append((r["class"], cur, r["resource"]))
    assert not bad, bad
    assert len(now) == len(rows), (len(now), len(rows))
    print(f"verified: {len(rows)}/{len(rows)} objects reference their SAM_GH_* icon resource")


def main():
    rows = json.load(open(os.path.join(DESIGN, "manifest.json"), encoding="utf-8"))
    by_proj = {}
    for r in rows:
        by_proj.setdefault(r["project_dir"], []).append(r)
    for pdir_rel, items in sorted(by_proj.items()):
        pdir = os.path.join(REPO, pdir_rel)
        icon_dir = os.path.join(pdir, "Resources", "Icons")
        if os.path.isdir(icon_dir):
            shutil.rmtree(icon_dir)
        os.makedirs(icon_dir)
        names = {r["resource"]: r["icon_id"] for r in items}
        for res, iid in names.items():
            shutil.copyfile(os.path.join(PNG, iid + ".png"), os.path.join(icon_dir, res + ".png"))
        holders = {r["icon_holder"] for r in items}
        assert len(holders) == 1, (pdir_rel, holders)
        holder = holders.pop()
        if holder == "Resources":
            designer = os.path.join(pdir, "Properties", "Resources.Designer.cs")
            kinds = {resource_is_bytes(designer, r["current_icon"]) for r in items if not r["current_icon"].startswith(PREFIX)}
            if not kinds:  # re-run: all getters already point at generated resources
                kinds = {resource_is_bytes(designer, items[0]["resource"])}
            assert len(kinds) == 1, (pdir_rel, "mixed byte[]/Bitmap icon resources")
            as_bytes = kinds.pop()
            update_resx(os.path.join(pdir, "Properties", "Resources.resx"), names, as_bytes)
            update_designer(designer, names, as_bytes)
            mech = "resx/" + ("byte[]" if as_bytes else "Bitmap")
        else:
            hp = [os.path.join(root, f) for root, _, fs in os.walk(pdir) for f in fs
                  if f == holder + ".cs" and "obj" not in root.split(os.sep)]
            assert len(hp) == 1, (pdir_rel, holder, hp)
            csproj = [os.path.join(pdir, f) for f in os.listdir(pdir) if f.endswith(".csproj")][0]
            update_holder(hp[0], names, csproj)
            mech = "holder/" + holder
        for r in items:
            update_icon(os.path.join(REPO, r["source"]), r["class"], holder, r["resource"], r["guid"])
            r["status"] = "integrated"
        print(f"{r['project']}: {len(items)} objects, {len(names)} icon resources ({mech})")
    verify(rows)
    json.dump(rows, open(os.path.join(DESIGN, "manifest.json"), "w", encoding="utf-8"), indent=1)
    import csv
    with open(os.path.join(DESIGN, "manifest.csv"), "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)


if __name__ == "__main__":
    main()
